name: Build/release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm run requirement
      
      - name: Build VencordExtension
        run: npm run vencord

      - name: Build JS Code
        run: npm run build:ts

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload multiple files
        uses: actions/upload-artifact@v5
        with:
          name: DiscordBotClient-nightly-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.AppImage
            dist/*.dmg

