name: Lint
on:
  push:
    branches: 
      - electron-v3
  pull_request:
    branches:
      - electron-v3

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm install --verbose

      - run: npm run lint

      - run: npm run test:typescript
